- create:
    - ~/.config/htop/
    - ~/.config/pgcli/
    - ~/.config/youtube-dl/

- clean:
    - "~/"
    - "~/.config/htop/"
    - "~/.config/pgcli/"
    - "~/.config/youtube-dl/"

- link:
    ~/.digrc: misc/digrc
    ~/.gemrc: misc/gemrc
    ~/.mtrrc: misc/mtrrc
    ~/.wgetrc: misc/wgetrc
    ~/.curlrc: misc/curlrc
    ~/.psqlrc: misc/psqlrc
    ~/.myclirc: mycli/config
    ~/.Xresources: misc/Xresources
    ~/.config/htop/htoprc: misc/htoprc
    ~/.ansiweatherrc: misc/ansiweatherrc
    ~/.config/pgcli/config: pgcli/config
    ~/.config/youtube-dl/config: youtube-dl/config
