[tools]
age = "latest"
age-plugin-yubikey = "latest"
amazon-ecr-credential-helper = "latest"
argocd = "latest"
"aqua:argoproj-labs/argocd-image-updater" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
azure = "latest"
caddy = "latest"
cfssl = "latest"
cheat = "latest"
checkov = "latest"
cloud-sql-proxy = "latest"
cloudflared = "latest"
cmctl = "latest"
conftest = "latest"
cue = "latest"
doggo = "latest"
dua = "latest"
flyctl = "latest"
gallery-dl = "latest"
gdu = "latest"
github-cli = "latest"
go = "latest"
golangci-lint = "latest"
hadolint = "latest"
helm = "latest"
helm-cr = "latest"
helm-ct = "latest"
helm-diff = "latest"
helmfile = "latest"
hugo = "latest"
infracost = "latest"
jc = "latest"
jd = "latest"
jnv = "latest"
jq = "latest"
jqp = "latest"
jwt = "latest"
jwtui = "latest"
k6 = "latest"
k9s = "latest"
ksops = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
kubespy = "latest"
kustomize = "latest"
mitmproxy = "latest"
mkcert = "latest"
nomad = "latest"
opa = "latest"
packer = "latest"
pandoc = "latest"
powerpipe = "latest"
qsv = "latest"
rclone = "latest"
rust = "stable"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
stack = "latest"
steampipe = "latest"
stern = "latest"
telepresence = "latest"
terraform = "latest"
terraform-docs = "latest"
terraform-ls = "latest"
terraformer = "latest"
tf-summarize = "latest"
tflint = "latest"
tfsec = "latest"
tfstate-lookup = "latest"
trdsql = "latest"
"ubi:harelba/q" = "latest"
"ubi:johnkerl/miller" = { version = "latest", exe = "mlr" }
"ubi:rgburke/grv" = "latest"
upx = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
yamlfmt = "latest"
yq = "latest"
"ubi:haskell/stylish-haskell" = "latest"
"ubi:remko/age-plugin-se" = "latest"
"ubi:str4d/rage" = "latest"
"ubi:exercism/cli" = { version = "latest", exe = "exercism" }
"ubi:variadico/noti" = "latest"
"ubi:PostgREST/postgrest" = "latest"
"ubi:gitlab-org/cli" = { version = "latest", exe = "glab", provider = "gitlab" }
ast-grep = "latest"
minisign = "latest"
node = "lts"
usql = "latest"
